import Head from "next/head";
import Homepage from "../components/Homepage";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blogging Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Homepage
        heading="WriteMind"
        message="Welcome to WriteMind, a platform for sharing thoughts, experiences,
        and insights on a variety of topics ."
      />
    </div>
  );
}
